### ISSUE TITLE
Avoir un service en production

### ISSUE THREAD

**Issue by guillett** [betagouv/lapin#259]
Un premier objectif qui me paraît intéressant est d'avoir un service en ligne et en production

- [ ]  sur https://(www.)?rdv-solidarites.fr/
- [ ] avec une base de données pérenne (qu'on ne va pas détruire après expérimentation)

WDYT ?

**Comment by mmagn** [comment]
Ça tombe bien c'était un de nos objectifs de la semaine.
On en parle demain à la démo.
